- name: jito-solana repository
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/jito-foundation/jito-solana.git'
    dest: /mnt/solana
    version: tags/{{ jito_solana_version }}

- name: build jito-solana
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && /mnt/solana/cargo build --release
  args:
    chdir: /mnt/solana
    executable: /bin/bash
