# set environment variables for jito client
- name: add relayer url environment variable
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: RELAYER_URL={{ jito_relayer_url }}
    create: yes

- name: add block engine url environment variable
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: BLOCK_ENGINE_URL={{ jito_block_engine_url }}
    create: yes

- name: add shred receiver environment variable
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: SHRED_RECEIVER_ADDR={{ jito_shred_receiver_url }}
    create: yes

- name: copy validator keys
  become: true
  become_user: solana
  ansible.builtin.copy:
    src: files/keys/mainnet.json
    dest: /home/solana/.identity.json
    owner: solana
    group: solana
    mode: '0600'